# Nome da aplicação
spring.application.name=logitrack-pro

# Conexão com o Banco do Docker (Porta 5444)
spring.datasource.url=jdbc:postgresql://localhost:5444/logitrack_db
spring.datasource.username=logi_user
spring.datasource.password=logi_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate (JPA)
# 'validate' garante que o Java bata com o banco que subimos
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuração de Segurança (Para o JWT que vamos criar)
# Defina uma chave secreta aleatória com pelo menos 32 caracteres aqui
jwt.secret=sua_chave_secreta_muito_longa_e_segura_123456
jwt.expiration=3600000